### ISSUE TITLE
Translate new / missing message for Chinese language

### ISSUE THREAD

**Issue by schmidt-uni-leipzig** [DigitalDataChainConsortium/vdi2770#12]
Please provide Chinese translations for the following messages (the messages keys, like RD_LABEL_TITLE shall not be translated).

### Messages of the PDF report

RD_LABEL_TITLE=VDI 2770 Container Validation Result
RD_LABEL_SEC_OVERVIEW=Overview
RD_LABEL_OVERVIEW_HEADER_FILE=Filename
RD_LABEL_OVERVIEW_HEADER_ERRORCOUNT=Error Count
RD_LABEL_OVERVIEW_HEADER_WARNCOUNT=Warning Count
RD_LABEL_SEC_REPORT=Report on
RD_LABEL_SEC_ERRORS=Validation Errors
RD_LABEL_SEC_WARNINGS=Validation Warnings
RD_LABEL_SEC_INFO=Validation Info
RD_LABEL_NOMESSAGE=No messages available.
RD_LABEL_SEC_SUPREPORTS=Sub Reports
RD_LABEL_PAGE=page
PV_EXCEPTION_010=PV_010 File {0} is not a PDF file.
PV_MESSAGE_002=PV_002 PDF preflight failed for PDF file {0}.

### Messages for PDF validation (see issue #4)

REP_MESSAGE_040=REP_040 The PDF file {0} is encrypted or password protected.
REP_MESSAGE_041=REP_041 PDF file {0} is not encrypted.
REP_MESSAGE_042=REP_042 Unable to check encryption for PDF file {0}: {1}.
REP_MESSAGE_043=REP_043 PDF file {0} contains text.
REP_MESSAGE_044=REP_044 PDF file {0} does not contain text.
REP_MESSAGE_045=REP_045 Unable to extract text from PDF file {0}.
REP_MESSAGE_046=REP_046 Cannot validate PDF file {0}.
REP_MESSAGE_047=REP_047 PDF Validation Problem: {0}

### Message for the web backend

RS_MESSAGE_001=Unsupported MIME Type {0}

REH_MESSAGE_001=Uploaded file exceeds maximum file size of {0}
REH_MESSAGE_002=Uploaded file exceeds maximum file size
REH_MESSAGE_003=Error while uploading file

BC_MESSAGE_001=Invalid API parameter call. 
BC_MESSAGE_002=Internal error.

**Comment by Brezel31** [comment]
Translation attached
[uebersetzung_feb_22.xlsx](https://github.com/DigitalDataChainConsortium/vdi2770/files/8141592/uebersetzung_feb_22.xlsx)
