### ISSUE TITLE
Allow PDF format variants in document containers

### ISSUE THREAD

**Issue by janoevermann** [DigitalDataChainConsortium/vdi2770#17]
## What is the current behavior?
A document container with a valid PDF/A and a (regular) PDF as format variant will throw a validation error.  
(""REP_017 Konnte PDF/A Level von Korrekturblatt_26882736_FV2.pdf nicht auslesen.")

Corresponding Report:
[hwgFECzh7mkNFPw2 (1).pdf](https://github.com/DigitalDataChainConsortium/vdi2770/files/9138880/hwgFECzh7mkNFPw2.1.pdf)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Generate a VDI 2770 documentation container, which contains a VDI 2770 document container, which contains two PDF documents (one PDF/A, and one PDF).

## What is the expected behavior?
No error, because a valid PDF/A was provided. Validation should check if minimum one PDF/A is present.

![image](https://user-images.githubusercontent.com/50442313/179711975-349b2c9e-58dc-4eb8-a825-716046c14aca.png)

Specification, page 32: "[...] any desired file format"

## What is the motivation / use case for changing the behavior?
1) Providers of test certificates need to provide cryptographically signed reports which may not be compatible with PDF/A
2) Use of automated converters (PDF->PDF/A) and providing converted ODF/A alongside the original

## Example
See attached validaton report. The correspondig container can be provided upon request.

## Please tell us about your environment:
Validator hosted on the DDCC website

**Comment by schmidt-uni-leipzig** [comment]
I can see the point. According to VDI 2770 a PDF/A representation is required and other files may be provided. So, in your case, there is a PDF/A file and another PDF file that does not conform to PDF/A or may be encrypted. You expect that the "valid PDF/A file" is the PDF/A representation (see red file in the figure) and the other PDF file may be "other format" (see dark grey file in the figure).

To be discussed: VDI 2770 does not mark files as "this is the PDF/A file". so, we could check every file, if it is a PDF file. Than, we may check, if at least one of the PDF files is a PDF/A file that is valid. If this is the case, the validator shall not report an error or warning if there is another PDF file that is not a PDF/A file.

**Comment by schmidt-uni-leipzig** [comment]
Commit [216f079](https://github.com/DigitalDataChainConsortium/vdi2770/commit/216f0792dde7dbb0db802fc8f91fa033d0f5ae68) represents an initial proposal for implementation. For each file in the container the mime types are evaluated and reported. The PDF file(s) are then checked separately (PDF/A level, text readable, etc.). If at least one PDF is valid, then the other PDF files are not validated with error level but with info level. This means that all PDF files are validated (with at least informative messages). 

Another possibility would be not to validate the "other" PDF files then and only report the PDF/A file.

All in all, however, it is clear that VDI 2770should also specify a fixed name for the PDF file in a document container. Then this check would be easier to implement.

@janoevermann Could you review the code and give me a feedback, please?

**Comment by schmidt-uni-leipzig** [comment]
Added fix in develop branch. issue can be closed.
