### ISSUE TITLE
Why the following container fails in the validation?

### ISSUE THREAD

**Issue by ikercrg** [DigitalDataChainConsortium/vdi2770#28]
## What is the current behavior?
Using the validator under -> https://www.digitaldatachain.com/portal/fep/en/dt.jsp?setCursor=1_542800, the validation fails and I get some errors that I do not understand.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Find attached the zip container and just validate it against the validator in your page (or against your running app)
[test_a_serial.zip](https://github.com/DigitalDataChainConsortium/vdi2770/files/10092557/test_a_serial.zip)

These are the errors in main.xml

Validation Errors
D_004 Found document relationship to an unknown document ID
doc2;Test;false.
D_004 Found document relationship to an unknown document ID
doc1;Test;false.

and this one in each metadata.xml
REP_039 XML file is not valid. Skipping further XML analysis.

All generated xml are generated with this schema:

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.vdi.de/schemas/vdi2770"
           targetNamespace="http://www.vdi.de/schemas/vdi2770" elementFormDefault="qualified" attributeFormDefault="unqualified"
           version="2019-08-23">
....

I know that this is not an issue, but I do not know where to ask it. Any help would be appreciate it.

**Comment by ikercrg** [comment]
it was the release data

**Comment by schmidt-uni-leipzig** [comment]
Please excuse the late reply. Glad you found the error yourself. Your are right: the internal validation message reports the problem: `Text '2010-04-01+02:00' could not be parsed`. This message is not shon in the validation report. So, I re-open this issue and planned it for the next release.

**Comment by schmidt-uni-leipzig** [comment]
In case of a XML error, the report contains messages with the ID REP_016 followed by error messages like `XML file is invalid at line 36: ...` with the ID REP_023. 

Notice: These messages are provided in the requested language, but in seldom cases, the system default language is used.
